interface Project {
  title: string;
  idea: string;
  targetAudience?: string;
  problem?: string;
  createdAt: Date;
  outputs: Array<{ step: number; stepName: string; content: any; rawText: string }>;
}

/**
 * Generates a clean Markdown export of the full startup blueprint.
 */
export function generateMarkdownExport(project: Project, stepLabels: Record<number, string>): string {
  const date = new Date(project.createdAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const lines: string[] = [
    `# ${project.title} — Startup Blueprint`,
    ``,
    `> Generated by AI Startup Builder on ${date}`,
    ``,
    `---`,
    ``,
    `## Idea Overview`,
    ``,
    `**Idea:** ${project.idea}`,
    project.targetAudience ? `**Target Audience:** ${project.targetAudience}` : '',
    project.problem ? `**Problem:** ${project.problem}` : '',
    ``,
    `---`,
    ``,
  ];

  for (const output of project.outputs) {
    const label = stepLabels[output.step] || output.stepName;
    lines.push(`## Step ${output.step}: ${label}`);
    lines.push('');

    // Try to render JSON as clean markdown
    try {
      const parsed = typeof output.content === 'string'
        ? JSON.parse(output.content)
        : output.content;

      lines.push(renderJsonAsMarkdown(parsed, 0));
    } catch {
      lines.push(output.rawText);
    }

    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push(`*Blueprint generated by [AI Startup Builder](https://aistartupbuilder.com)*`);

  return lines.filter(l => l !== undefined).join('\n');
}

function renderJsonAsMarkdown(obj: any, depth: number): string {
  if (typeof obj === 'string') return obj;
  if (typeof obj === 'number' || typeof obj === 'boolean') return String(obj);
  if (obj === null || obj === undefined) return '';

  if (Array.isArray(obj)) {
    return obj.map((item) => {
      if (typeof item === 'object' && item !== null) {
        return `- ${renderJsonAsMarkdown(item, depth + 1)}`;
      }
      return `- ${item}`;
    }).join('\n');
  }

  if (typeof obj === 'object') {
    const entries = Object.entries(obj);
    return entries.map(([key, value]) => {
      const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());

      if (Array.isArray(value)) {
        const items = value.map((v) => {
          if (typeof v === 'object' && v !== null) {
            return `  - ${Object.entries(v).map(([k, val]) => `**${k}**: ${val}`).join(' · ')}`;
          }
          return `  - ${v}`;
        }).join('\n');
        return `**${label}:**\n${items}`;
      }

      if (typeof value === 'object' && value !== null) {
        const nested = Object.entries(value as object).map(([k, v]) => `  - **${k}**: ${v}`).join('\n');
        return `**${label}:**\n${nested}`;
      }

      return `**${label}:** ${value}`;
    }).join('\n\n');
  }

  return String(obj);
}
